name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        #      - uses: bufbuild/buf-breaking-action@v1
        #        with:
        #          # The 'main' branch of the GitHub repository that defines the module.
        #          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
      -
        name: Install Protoc
        uses: arduino/setup-protoc@v1
      -
        name: Install python dependencies
        run: pip install grpclib grpcio-tools
      -
        name: Generate code
        run: buf generate
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build gateway
        uses: docker/build-push-action@v3
        with:
          context: gateway
          target: gateway

          push: false
          tags: magmax/sekura-gateway:latest
