name: buf-push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        #      - uses: bufbuild/buf-breaking-action@v1
        #        with:
        #          # The 'main' branch of the GitHub repository that defines the module.
        #          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1"
      -
        name:  Install dependencies for gateway
        run: go install
        working-directory: gateway
      -
        name: Generate code for gateway
        run: poetry run buf generate
      -
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: magmax/sekura-gateway
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: gateway
          target: gateway
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
